
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import messagebox
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/arnavkanwar/Desktop/OpppPo/build/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

# Predefined user data (username: password)
user_data = {
    "user1": "password1",
    "user2": "password2",
    "admin": "adminpass"
}



# Function to handle login
def login():
    username = entry_username.get()
    password = entry_password.get()
        # Check if the username exists and the password matches
    if username in user_data and user_data[username] == password:
       messagebox.showinfo("Login Success", f"Welcome, {username}!")
    else:
        messagebox.showerror("Login Failed", "Invalid username or password.")


window = Tk()

window.geometry("1024x786")
window.configure(bg = "#6A6A6B")


canvas = Canvas(
    window,
    bg = "#6A6A6B",
    height = 786,
    width = 1024,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    229.0,
    378.0,
    image=image_image_1
)

canvas.create_text(
    94.0,
    40.0,
    anchor="nw",
    text="WELCOME TO LMS",
    fill="#FFFFFF",
    font=("Inter ExtraBoldItalic", 74 * -1)
)

canvas.create_rectangle(
    490.0,
    186.0,
    924.0,
    626.0,
    fill="#9C9C9E",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    707.0,
    502.0,
    image=entry_image_1
)
entry_password = Entry(
    bd=0,
    bg="#FFFDFD",
    fg="#000716",
    highlightthickness=0
)
entry_password.place(
    x=571.0,
    y=486.0,
    width=272.0,
    height=30.0
)

canvas.create_text(
    555.0,
    253.0,
    anchor="nw",
    text="Username",
    fill="#000000",
    font=("Inter ExtraBoldItalic", 36 * -1)
)

canvas.create_text(
    555.0,
    413.0,
    anchor="nw",
    text="Password",
    fill="#000000",
    font=("Inter ExtraBoldItalic", 36 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    707.0,
    329.0,
    image=entry_image_2
)
entry_username = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_username.place(
    x=571.0,
    y=313.0,
    width=272.0,
    height=30.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=login,
    relief="flat"
)
button_1.place(
    x=631.0,
    y=570.0,
    width=152.0,
    height=32.0
)
window.resizable(False, False)
window.mainloop()
